name: Renew Trustlist DE

on:
  schedule:
    - cron: '0 5,10,15,20 * * *'
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download a file
        run: curl https://de.dscg.ubirch.com/trustList/DSC -o trustlist_de.min.json
      - name: cleanup file
        run: tail -n +2 trustlist_de.min.json > trustlist_de.min.json.tmp && mv trustlist_de.min.json.tmp trustlist_de.min.json
      - name: pretty print json
        run: cat trustlist_de.min.json | python -m json.tool > trustlist_de.json
      - uses: EndBug/add-and-commit@v7
        with:
          author_name: github action download trustlist
          message: 'Update Trustlist DE'
          add: '*.json'
